version: '3.1'

services: 
  vsserver:
    build:
      context: .
      args: 
        vs_data_path: /gamedata/vs-mods/
    container_name: vsserver
    restart: always
    volumes: 
      - gamedata:/gamedata
    ports:
      - 42420:42420
      
volumes:
  gamedata: