version: '3.8'

services: 
  vsserver:
    build:
      context: .
      args: 
        vs_data_path: /gamedata/vs-custom/
    container_name: vsserver
    restart: always
    volumes: 
      - gamedata:/gamedata
    ports:
      - target: 42420
        published: 42420
        protocol: tcp
        # mode: host
    environment:
      VS_DATA_PATH: /gamedata/vs-custom
volumes:
  gamedata: